/*  
 *  Author: Brian Moye
 *  Purpose:
 *  Create a GUI program that allows a user to:
 *      Enter a rental time in hours, if the input isn't numeric set it to 0.
 *      Choose one equipment type from 7 different choices.
 *          $40 for Personal Watercraft and Pontoon Boat
 *          $20 for Rowboat, Canoe, and Kayak
 *          $7 for Beach Chair and Umbrella
 *          $5 for optional Equipment Lesson
 *      Display a message with the details of the rental, including total price.
 */ 

package SammysRentals;

import java.awt.event.*;
import java.text.DecimalFormat;

public class SammysSeashoreRentals extends javax.swing.JFrame implements ActionListener, ItemListener {

    final int FORTY_PER_HOUR = 40;
    final int TWENTY_PER_HOUR = 20;
    final int SEVEN_PER_HOUR = 7;
    final int EQUIPMENT_LESSON_PRICE = 5;
    
    int selectedPrice = 0, hours = 0;
    String selection = "", equipment = "";
    DecimalFormat currency = new DecimalFormat("$###,##0.00");
    
    public SammysSeashoreRentals() {
        initComponents();
        initListeners();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpRentalOptions = new javax.swing.ButtonGroup();
        labelSammysRental = new javax.swing.JLabel();
        btnWatercraft = new javax.swing.JRadioButton();
        btnPontoon = new javax.swing.JRadioButton();
        btnRowboat = new javax.swing.JRadioButton();
        label40PerHour = new javax.swing.JLabel();
        label20PerHour = new javax.swing.JLabel();
        btnCanoe = new javax.swing.JRadioButton();
        btnKayak = new javax.swing.JRadioButton();
        label7PerHour = new javax.swing.JLabel();
        boxEquipmentLesson = new javax.swing.JCheckBox();
        btnBeachChair = new javax.swing.JRadioButton();
        btnUmbrella = new javax.swing.JRadioButton();
        labelHoursToRent = new javax.swing.JLabel();
        textFieldRentalHours = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSelection = new javax.swing.JTextArea();
        btnInvisible = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sammy's Seashore Rentals");

        labelSammysRental.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSammysRental.setText("Sammy's Seashore Rentals");

        btnGrpRentalOptions.add(btnWatercraft);
        btnWatercraft.setText("Personal Watercraft");

        btnGrpRentalOptions.add(btnPontoon);
        btnPontoon.setText("Pontoon Boat");

        btnGrpRentalOptions.add(btnRowboat);
        btnRowboat.setText("Rowboat");

        label40PerHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label40PerHour.setText("$40 per hour");

        label20PerHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label20PerHour.setText("$20 per hour");

        btnGrpRentalOptions.add(btnCanoe);
        btnCanoe.setText("Canoe");

        btnGrpRentalOptions.add(btnKayak);
        btnKayak.setText("Kayak");

        label7PerHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label7PerHour.setText("$7 per hour");

        boxEquipmentLesson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxEquipmentLesson.setText("$5 Equipment Lesson");

        btnGrpRentalOptions.add(btnBeachChair);
        btnBeachChair.setText("Beach Chair");

        btnGrpRentalOptions.add(btnUmbrella);
        btnUmbrella.setText("Umbrella");

        labelHoursToRent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHoursToRent.setText("Enter number of hours to rent:");

        textFieldRentalHours.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textFieldRentalHours.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnSubmit.setText("Submit");

        textAreaSelection.setEditable(false);
        textAreaSelection.setColumns(20);
        textAreaSelection.setRows(5);
        jScrollPane1.setViewportView(textAreaSelection);

        btnGrpRentalOptions.add(btnInvisible);
        btnInvisible.setSelected(true);
        btnInvisible.setText("Invisible");
        btnInvisible.setContentAreaFilled(false);
        btnInvisible.setEnabled(false);
        btnInvisible.setFocusable(false);
        btnInvisible.setRequestFocusEnabled(false);
        btnInvisible.setRolloverEnabled(false);

        btnReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnWatercraft)
                                    .addComponent(btnPontoon)
                                    .addComponent(label40PerHour))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label20PerHour)
                                    .addComponent(btnCanoe)
                                    .addComponent(btnRowboat)
                                    .addComponent(btnKayak))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBeachChair)
                                    .addComponent(label7PerHour)
                                    .addComponent(btnUmbrella)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelHoursToRent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldRentalHours, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReset)
                            .addComponent(boxEquipmentLesson))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInvisible)
                        .addGap(47, 47, 47)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(labelSammysRental)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelSammysRental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHoursToRent)
                            .addComponent(textFieldRentalHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label40PerHour)
                            .addComponent(label20PerHour)
                            .addComponent(label7PerHour))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnWatercraft)
                            .addComponent(btnRowboat)
                            .addComponent(btnBeachChair))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPontoon)
                            .addComponent(btnCanoe)
                            .addComponent(btnUmbrella))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKayak)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxEquipmentLesson)
                            .addComponent(btnInvisible)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // End of Form Editor
    
    // Add listeners for each of the buttons
    private void initListeners() {
        btnWatercraft.addItemListener(this);
        btnPontoon.addItemListener(this);
        btnRowboat.addItemListener(this);
        btnCanoe.addItemListener(this);
        btnKayak.addItemListener(this);
        btnBeachChair.addItemListener(this);
        btnUmbrella.addItemListener(this);
        boxEquipmentLesson.addItemListener(this);
        btnSubmit.addActionListener(this);
        btnReset.addActionListener(this);
        btnInvisible.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SammysSeashoreRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SammysSeashoreRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SammysSeashoreRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SammysSeashoreRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SammysSeashoreRentals().setVisible(true);
            }
        });
    }
    
    @Override
    public void actionPerformed(ActionEvent evt) {
        Object source = evt.getSource();
        int totalPrice = 0;
        
        if (source == btnSubmit) {
            try {
                hours = Integer.parseInt(textFieldRentalHours.getText());
            }
            catch(Exception all) {
                hours = 0;
            }
            
            totalPrice = hours * selectedPrice;
            
            if (boxEquipmentLesson.isSelected()) {
                totalPrice += EQUIPMENT_LESSON_PRICE;
                equipment = "Yes\n";
            }
            else {
                equipment = "No\n";
            }
            
            textAreaSelection.setText("Rental Details:\n\n" 
                + "Your chosen rental is a(n) " + selection + ".\n" 
                + "Your rental time is " + hours + " hour(s).\n\n" 
                + "Would you like an equipment lesson?\n" 
                + equipment + "\nTotal Price:\n" + currency.format(totalPrice));
        }
        
        if (source == btnReset) {
            btnInvisible.setSelected(true);
            boxEquipmentLesson.setSelected(false);
            textFieldRentalHours.setText("");
            textAreaSelection.setText("");
        }
    }
    
    @Override
    public void itemStateChanged(ItemEvent evt) {
        Object source = evt.getSource();
        
        // $7 per hour
        if (source == btnBeachChair) {
            selectedPrice = SEVEN_PER_HOUR;
            selection = "Beach Chair";
        }
        else if (source == btnUmbrella) {
            selectedPrice = SEVEN_PER_HOUR;
            selection = "Umbrella";
        }
        
        // $20 per hour
        else if (source == btnRowboat) {
            selectedPrice = TWENTY_PER_HOUR;
            selection = "Rowboat";
        }
        else if (source == btnCanoe) {
            selectedPrice = TWENTY_PER_HOUR;
            selection = "Canoe";
        }
        else if (source == btnKayak) {
            selectedPrice = TWENTY_PER_HOUR;
            selection = "Kayak";
        }
        
        // $40 per hour
        else if (source == btnWatercraft) {
            selectedPrice = FORTY_PER_HOUR;
            selection = "Personal Watercraft";
        }
        else if (source == btnPontoon) {
            selectedPrice = FORTY_PER_HOUR;
            selection = "Pontoon Boat";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxEquipmentLesson;
    private javax.swing.JRadioButton btnBeachChair;
    private javax.swing.JRadioButton btnCanoe;
    private javax.swing.ButtonGroup btnGrpRentalOptions;
    private javax.swing.JRadioButton btnInvisible;
    private javax.swing.JRadioButton btnKayak;
    private javax.swing.JRadioButton btnPontoon;
    private javax.swing.JButton btnReset;
    private javax.swing.JRadioButton btnRowboat;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton btnUmbrella;
    private javax.swing.JRadioButton btnWatercraft;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label20PerHour;
    private javax.swing.JLabel label40PerHour;
    private javax.swing.JLabel label7PerHour;
    private javax.swing.JLabel labelHoursToRent;
    private javax.swing.JLabel labelSammysRental;
    private javax.swing.JTextArea textAreaSelection;
    private javax.swing.JTextField textFieldRentalHours;
    // End of variables declaration//GEN-END:variables
}
